## 同步回调

### 问题

有时候，在你的代码环境可能会阻止断言执行，导致测试静默失败。

### 解决方案

QUnit提供了一个特殊的断言，用来定义一个测试用例中断言的总数。当测试完成后没有正确数量的断言就会失败，不管其他断言(如果有的话)的结果如何。

用法简单直白，只需要在测试开始时调用`expect()`，唯一的参数是期望的断言总数：

    test( "a test", function() {
      expect( 2 );
     
      function calc( x, operation ) {
        return operation( x );
      }
     
      var result = calc( 2, function( x ) {
        ok( true, "calc() calls operation function" );
        return x * x;
      });
     
      equal( result, 4, "2 square equals 4" );
    });

另外，期望的断言总数可以作为第二个参数传递给`test()`：

    test( "a test", 2, function() {
     
      function calc( x, operation ) {
        return operation( x );
      }
     
      var result = calc( 2, function( x ) {
        ok( true, "calc() calls operation function" );
        return x * x;
      });
     
      equal( result, 4, "2 square equals 4" );
    });

实例：

    test( "a test", 1, function() {
      var $body = $( "body" );
     
      $body.on( "click", function() {
        ok( true, "body was clicked!" );
      });
     
      $body.trigger( "click" );
    });

### 讨论

`expect()`只在测试回调时最有用。当所有的断言都运行在test函数的作用域内时， `expect()`没有额外的作用——防止断言运行的任何错误都会导致测试最终失败，因为TestRunner会捕获错误并让单元测试失败。

原文：[http://qunitjs.com/cookbook/#synchronous_callbacks]()

====================================================================



